"""Initial migration with constraints

Revision ID: 5f3d5465a8ab
Revises: 
Create Date: 2025-12-24 15:43:44.864369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f3d5465a8ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('alert_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('prediction', sa.String(length=50), nullable=False),
    sa.Column('attack_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rf_confidence', sa.Float(), nullable=False),
    sa.Column('if_confidence', sa.Float(), nullable=False),
    sa.Column('ae_reconstruction_error', sa.Float(), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('destination_ip', sa.String(length=45), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("attack_type IN ('Benign', 'DDoS', 'DoS', 'PortScan', 'BruteForce', 'WebAttack', 'Botnet', 'Infiltration', 'Exploit')", name='check_attack_type_valid'),
    sa.CheckConstraint("prediction IN ('Attack', 'Benign')", name='check_prediction_valid'),
    sa.CheckConstraint("status IN ('unreviewed', 'investigating', 'resolved', 'false_positive')", name='check_status_valid'),
    sa.CheckConstraint('ae_reconstruction_error >= 0.0', name='check_ae_error_positive'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='check_confidence_range'),
    sa.CheckConstraint('destination_port IS NULL OR (destination_port >= 0 AND destination_port <= 65535)', name='check_dest_port_range'),
    sa.CheckConstraint('if_confidence >= -1.0 AND if_confidence <= 1.0', name='check_if_confidence_range'),
    sa.CheckConstraint('rf_confidence >= 0.0 AND rf_confidence <= 1.0', name='check_rf_confidence_range'),
    sa.CheckConstraint('source_port IS NULL OR (source_port >= 0 AND source_port <= 65535)', name='check_source_port_range'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index('idx_prediction_confidence', 'alerts', ['prediction', 'confidence'], unique=False)
    op.create_index('idx_status_timestamp', 'alerts', ['status', 'timestamp'], unique=False)
    op.create_index('idx_timestamp_attack_type', 'alerts', ['timestamp', 'attack_type'], unique=False)
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alerts_attack_type'), 'alerts', ['attack_type'], unique=False)
    op.create_index(op.f('ix_alerts_prediction'), 'alerts', ['prediction'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_table('network_flows',
    sa.Column('flow_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('raw_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flow_id')
    )
    op.create_index('idx_network_flow_alert', 'network_flows', ['alert_id'], unique=False)
    op.create_index(op.f('ix_network_flows_alert_id'), 'network_flows', ['alert_id'], unique=True)
    op.create_index(op.f('ix_network_flows_flow_id'), 'network_flows', ['flow_id'], unique=False)
    op.create_table('shap_explanations',
    sa.Column('explanation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('shap_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('explanation_id')
    )
    op.create_index('idx_shap_alert', 'shap_explanations', ['alert_id'], unique=False)
    op.create_index('idx_shap_generated_at', 'shap_explanations', ['generated_at'], unique=False)
    op.create_index(op.f('ix_shap_explanations_alert_id'), 'shap_explanations', ['alert_id'], unique=True)
    op.create_index(op.f('ix_shap_explanations_explanation_id'), 'shap_explanations', ['explanation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shap_explanations_explanation_id'), table_name='shap_explanations')
    op.drop_index(op.f('ix_shap_explanations_alert_id'), table_name='shap_explanations')
    op.drop_index('idx_shap_generated_at', table_name='shap_explanations')
    op.drop_index('idx_shap_alert', table_name='shap_explanations')
    op.drop_table('shap_explanations')
    op.drop_index(op.f('ix_network_flows_flow_id'), table_name='network_flows')
    op.drop_index(op.f('ix_network_flows_alert_id'), table_name='network_flows')
    op.drop_index('idx_network_flow_alert', table_name='network_flows')
    op.drop_table('network_flows')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_prediction'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_attack_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.drop_index('idx_timestamp_attack_type', table_name='alerts')
    op.drop_index('idx_status_timestamp', table_name='alerts')
    op.drop_index('idx_prediction_confidence', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
